### ISSUE TITLE
Teleportation on a real quantum computer

### ISSUE THREAD

**Issue by YP-qt** [Qiskit/qiskit-textbook#24] opened 2019-10-05 14:48 UTC
### Informations

- **Qiskit version**: 0.12.1
- **Python version**: 3.7.3
- **Operating system**: macOS Mojave

### What is the current behavior?
The states output from teleportation implemented on real quantum computer should give results with c2=0 as highest bars, while bars for results of c1=1 should be smaller.
In other words, if we have a success teleportation, we should get high probabilities for c2=0, which is the initial state.
I tried with shutting down the notebook and running the code couple times but the error still exists.

### Steps to reproduce the problem
The source code can be found in the following link:
https://community.qiskit.org/textbook/ch-algorithms/teleportation.html

### What is the expected behavior?
The result is expected to produce error with extra states due to noise. 
![Screen Shot 2019-10-05 at 10 42 31 AM](https://user-images.githubusercontent.com/43248687/66256547-e8305580-e75c-11e9-8573-9a14dfe5131d.png)

### Suggested solutions
Update the textbook or introduce an alternative source to deploy real quantum computer.

**Comment by aasfaw** [comment] 2019-10-06 02:54
Thanks for bringing this here, @ajavadia, and thanks for your question @YP-qt. As mentioned, the ordering of the results $c_2c_1c_0$ is such that $c_2 = 0$ is showing as the highest probability in your measurement results. The results for $c_2 = 1$ are due to errors in the computation.

It's not clear to me what the issue is at this point. The counts make sense based on these discussions. 

You might try experimenting with specific backends. For instance, the newer generation of devices (vigo, ourense and yorktown) have lower error rates, and you might try running on one of them,

I'll close this now, but feel free to reopen if you have other questions, or create new issues as you read along the textbook.

**Closed by aasfaw** 2019-10-06 02:54 UTC
