### ISSUE TITLE
"Next button" navigation bug

### ISSUE THREAD

**Issue by starktech23** [Qiskit/qiskit-textbook#153] opened 2020-01-13 04:02 UTC
The button at the bottom to move to the next page/chapter redirects to the same page/chapter. Problem occurs only in the first chapter of every section from 0 to 6, i.e. Next button for 0.1 leads to 0.1 but 0.2 and 0.3 work fine, similarly for the subsequent sections.

**Comment by schwarmco** [comment] 2020-01-17 17:33
Duplicate of #128

**Closed** 2020-01-18 00:35 UTC
